'use client';

import { KnowledgeCard as KnowledgeCardType } from '@/types/demo';
import { Button } from '@/components/ui/Button';

interface KnowledgeCardProps {
  card: KnowledgeCardType;
  onEdit?: () => void;
  onExport?: () => void;
  onFinish?: () => void;
}

export function KnowledgeCard({ card, onEdit, onExport, onFinish }: KnowledgeCardProps) {
  return (
    <div className="max-w-2xl mx-auto animate-fadeIn">
      {/* Success Header */}
      <div className="text-center mb-6">
        <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-green-100 flex items-center justify-center">
          <svg className="w-8 h-8 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
        <h2 className="text-xl font-semibold text-gray-900">Knowledge Captured!</h2>
        <p className="text-gray-500 mt-1">
          Your expertise has been documented in a structured knowledge card.
        </p>
      </div>

      {/* Knowledge Card */}
      <div className="bg-white rounded-xl border-2 border-gray-200 overflow-hidden shadow-lg">
        {/* Card Header */}
        <div className="bg-gg-accent px-6 py-4">
          <div className="flex items-center gap-2 text-blue-100 text-sm mb-1">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            KNOWLEDGE CARD
          </div>
          <h3 className="text-xl font-bold text-white">{card.title}</h3>
          <p className="text-blue-100 text-sm mt-1">{card.subtitle}</p>
        </div>

        {/* Card Content */}
        <div className="p-6 space-y-6">
          {/* Trigger Conditions */}
          <Section
            icon="⚡"
            title="Trigger Conditions"
            color="red"
            items={card.triggerConditions}
          />

          {/* Actions */}
          <Section
            icon="✓"
            title="Actions"
            color="green"
            items={card.actions}
          />

          {/* Risks */}
          <Section
            icon="⚠"
            title="Risks"
            color="amber"
            items={card.risks}
          />

          {/* Removal Conditions */}
          <Section
            icon="🔄"
            title="Removal Conditions"
            color="blue"
            items={card.removalConditions}
          />
        </div>

        {/* Card Footer */}
        <div className="bg-gray-50 px-6 py-4 border-t border-gray-200">
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-500">
              Generated by Bridge AI
            </p>
            <div className="flex gap-3">
              {onEdit && (
                <Button variant="ghost" size="sm" onClick={onEdit}>
                  <svg className="w-4 h-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                  Edit
                </Button>
              )}
              {onExport && (
                <Button variant="secondary" size="sm" onClick={onExport}>
                  <svg className="w-4 h-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                  </svg>
                  Export
                </Button>
              )}
              {onFinish && (
                <Button onClick={onFinish}>
                  <svg className="w-4 h-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  Complete Offboarding
                </Button>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* What's Next */}
      <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
        <h4 className="font-medium text-blue-900 mb-2">What happens next?</h4>
        <ul className="text-sm text-blue-800 space-y-1">
          <li>• This knowledge card will be reviewed by your team</li>
          <li>• An AI agent will be trained on this information</li>
          <li>• Your colleagues can query the agent for this expertise</li>
        </ul>
      </div>
    </div>
  );
}

// ========== Section Component ==========

interface SectionProps {
  icon: string;
  title: string;
  color: 'red' | 'green' | 'amber' | 'blue';
  items: string[];
}

function Section({ icon, title, color, items }: SectionProps) {
  const colorClasses = {
    red: 'bg-red-100 text-red-700',
    green: 'bg-green-100 text-green-700',
    amber: 'bg-amber-100 text-amber-700',
    blue: 'bg-blue-100 text-blue-700',
  };

  const bulletColors = {
    red: 'text-red-500',
    green: 'text-green-500',
    amber: 'text-amber-500',
    blue: 'text-blue-500',
  };

  return (
    <div>
      <div className="flex items-center gap-2 mb-3">
        <span className={`w-7 h-7 rounded-lg flex items-center justify-center text-sm ${colorClasses[color]}`}>
          {icon}
        </span>
        <h4 className="font-semibold text-gray-900">{title}</h4>
      </div>
      <ul className="space-y-2 ml-9">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-2">
            <span className={`mt-1.5 ${bulletColors[color]}`}>•</span>
            <span className="text-gray-700 text-sm">{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
